Fixed third_part.py get_section_option returning the results
with double quotes, causing the channel_manager to throw the
following error, due to:
os.path.join( *args ) ['git', 'pull', '--rebase'] F:\SublimeText\Data\"Packages/C#"

:20:37:55:603.029966 2.54e+00 - channel_manager.submodules_manager.run_general_command:423 - 18.22%, 00:01:57 of 00:08:47,  46(45) of 247... submodule "Packages/C#"
error: PackagesManager

Error executing: git pull --rebase

[WinError 267] The directory name is invalid

Try checking your "None_binary" setting?

                If there will be new messages on the next seconds,
                they will be show on the Sublime Text console