Renamed setup back to setup.py because pip install was not finding
FileNotFoundError: [Errno 2] No such file or directory: 'AppData\\Local\\Temp\\pip-build-6hz7j8da\\plantuml-connection\\setup.py'